### ISSUE TITLE
No license?

### ISSUE THREAD

**Issue by BitPuffin** [tonyg/rmacs#1]
Hello! As I've mentioned to you in irc, I love what this project is doing (though it doesn't look very active right now).

I was pondering if maybe I should attempt to use racket gui to add gui support for rmacs, as I can't use the meta key in a mac os x terminal (ffs apple). However then I noticed that there seems to be no license for rmacs, unless I'm totally blind. This means that you still have full copyright and it's actually not really legal for me to change the source at all. So you should probably specify a license. As always, I recommend CC0 or maybe MIT. But pick whatever you want. Though preferable something that let's users pick their own license when making extensions (IE not GPL) IMO.

Cheers man :)

**Comment by tonyg** [comment]
Excellent point! It'll be LGPL, like the core Racket codebase.
