### ISSUE TITLE
Instructions to build/use?

### ISSUE THREAD

**Issue by joelmccracken** [tonyg/rmacs#2]
I cloned the repo and was interested in trying it out, but I immediately got this error:

```
37  Joels-MBP in ~/Projects/rmacs
±  |master ✓| → make
raco setup rmacs
collection-path: collection not found
  collection: "rmacs"
  in collection directories:
   /Users/joel/Library/Racket/6.1.1/collects
   /opt/homebrew-cask/Caskroom/racket/6.1.1/Racket v6.1.1/collects
   ... [155 additional linked and package directories]
make: *** [setup] Error 1
```

Thoughts? Should I be doing something else to try this?

**Comment by tonyg** [comment]
Thanks! Good point. I've added a few notes to the README -- let me know if they help you, or if more/different text needs to be written.

**Comment by joelmccracken** [comment]
That worked! Neat.

Only other problem I had was that the rmacs bin wasn't actually in my path, but I think that's an install/setup problem, and reading the output of make told me whats up. 

There are display problems, but this is a WIP, so that's expected. 

Thanks!
