### ISSUE TITLE
raco setup: error: during making for <pkgs>/rmacs/rmacs/mode

### ISSUE THREAD

**Issue by xieyuheng** [tonyg/rmacs#3]
- (eshell)
  eshell number 1
  the main eshell for this frame
  
  ~
  raco setup rmacs

raco setup: version: 6.2.1 [3m]
raco setup: installation name: 6.2.1
raco setup: variants: 3m
raco setup: main collects: /usr/share/racket/collects
raco setup: collects paths: 
raco setup:   /home/xyh/.racket/6.2.1/collects
raco setup:   /usr/share/racket/collects
raco setup: main pkgs: /usr/share/racket/pkgs
raco setup: pkgs paths: 
raco setup:   /usr/share/racket/pkgs
raco setup:   /home/xyh/.racket/6.2.1/pkgs
raco setup: links files: 
raco setup:   /usr/share/racket/links.rktd
raco setup:   /home/xyh/.racket/6.2.1/links.rktd
raco setup: main docs: /usr/share/doc/racket
raco setup: --- updating info-domain tables ---
raco setup: --- pre-installing collections ---
raco setup: --- installing foreign libraries ---
raco setup: --- installing shared files ---
raco setup: --- compiling collections ---
raco setup: --- parallel build using 4 jobs ---
raco setup: 3 making: <pkgs>/rmacs/rmacs (editor)
raco setup: 3 making: <pkgs>/rmacs/rmacs/mode
lang/racket/app/rmacs/rmacs/mode/fundamental.rkt:7:20: except-in: identifier `string-prefix?' not included in nested require spec
  at: racket/string
  in: (except-in racket/string string-prefix?)
  compilation context...:
   /home/xyh/lang/racket/app/rmacs/rmacs/mode/fundamental.rkt
  context...:
   /usr/share/racket/collects/racket/private/reqprov.rkt:497:5
   /usr/share/racket/collects/racket/require-transform.rkt:266:2: expand-import
   try-next
   /usr/share/racket/collects/racket/private/reqprov.rkt:243:2
   /usr/share/racket/collects/syntax/wrap-modbeg.rkt:46:4
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   /usr/share/racket/collects/compiler/cm.rkt:628:2: do-check
   /usr/share/racket/collects/compiler/cm.rkt:708:4
   /usr/share/racket/collects/setup/parallel-do.rkt:431:20: loop
lang/racket/app/rmacs/rmacs/mode/fundamental.rkt:7:20: except-in: identifier`string-prefix?' not included in nested require spec
  at: racket/string
  in: (except-in racket/string string-prefix?)
  compilation context...:
   /home/xyh/lang/racket/app/rmacs/rmacs/mode/fundamental.rkt
   /home/xyh/lang/racket/app/rmacs/rmacs/main.rkt
  context...:
   /usr/share/racket/collects/racket/private/reqprov.rkt:497:5
   /usr/share/racket/collects/racket/require-transform.rkt:266:2: expand-import
   try-next
   /usr/share/racket/collects/racket/private/reqprov.rkt:243:2
   /usr/share/racket/collects/syntax/wrap-modbeg.rkt:46:4
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   /usr/share/racket/collects/compiler/cm.rkt:628:2: do-check
   /usr/share/racket/collects/compiler/cm.rkt:744:4: compilation-manager-load-handler
   standard-module-name-resolver
   /usr/share/racket/collects/compiler/cm.rkt:341:0: compile-zo*
   /usr/share/racket/collects/compiler/cm.rkt:556:26
   /usr/share/racket/collects/compiler/cm.rkt:548:42
   /usr/share/racket/collects/compiler/cm.rkt:513:0: maybe-compile-zo
   ...
raco setup: --- creating launchers ---
raco setup: launcher: /home/xyh/.racket/6.2.1/bin/rmacs
raco setup: --- installing man pages ---
raco setup: --- building documentation ---
raco setup: --- installing collections ---
raco setup: --- post-installing collections ---
raco setup: --- summary of errors ---
raco setup: error: during making for <pkgs>/rmacs/rmacs/mode
raco setup:   lang/racket/app/rmacs/rmacs/mode/fundamental.rkt:7:20: except-in: identifier `string-prefix?' not included in nested require spec
raco setup:     at: racket/string
raco setup:     in: (except-in racket/string string-prefix?)
raco setup:     compiling: <pkgs>/rmacs/rmacs/mode/fundamental.rkt
raco setup: error: during making for <pkgs>/rmacs/rmacs (editor)
raco setup:   lang/racket/app/rmacs/rmacs/mode/fundamental.rkt:7:20: except-in: identifier`string-prefix?' not included in nested require spec
raco setup:     at: racket/string
raco setup:     in: (except-in racket/string string-prefix?)
raco setup:     compiling: <pkgs>/rmacs/rmacs/mode/fundamental.rkt

1  ~

**Comment by tonyg** [comment]
I think this was caused by using a slightly older Racket than the version I am using. Try upgrading Racket and see if the problem is gone.
