### ISSUE TITLE
rmacs not launching on Mac OS X 10.11.6 with Racket 6.8

### ISSUE THREAD

**Issue by stevebyan** [tonyg/rmacs#4]
I installed rmacs using the DrRacket package manager, added ~/Library/Racket/bin to my PATH, and tried to run rmacs from Terminal.app:

smb$ rmacs
link: bad variable linkage;
 reference to a variable that is uninitialized
  reference phase level: 0
  variable module: "/Users/smb/Library/Racket/6.8/pkgs/unix-signals/unix-signals/private/unix-signals-extension.rkt"
  variable phase: 0
  reference in module: "/Users/smb/Library/Racket/6.8/pkgs/unix-signals/unix-signals/main.rkt"
  in: get-signal-fd
  context...:
   /Users/smb/Library/Racket/6.8/pkgs/unix-signals/unix-signals/main.rkt: [running body]
   /Users/smb/Library/Racket/6.8/pkgs/rmacs/rmacs/display-terminal.rkt: [traversing imports]
   /Users/smb/Library/Racket/6.8/pkgs/rmacs/rmacs/editor.rkt: [traversing imports]
   /Users/smb/Library/Racket/6.8/pkgs/rmacs/rmacs/main.rkt: [traversing imports]
smb$

**Comment by tonyg** [comment]
Hmm, I don't see that here on my 10.11.6 installation. One difference could be that I installed it from a git checkout, but surely that can't be it! ("Surely!")

Could you try running `raco setup`, and then trying again?

**Comment by tonyg** [comment]
OK, this is weird. I've pinned it down to an interaction between `ansi` and `unix-signals`. This program runs fine on Linux, but not OSX 10.11.6:

```racket
#lang racket
(require ansi)
(require unix-signals)
```

When it fails, it fails with exactly the error you are seeing, Steve.

Could it be possible that there's some kind of linker-related interference between the `scheme_module_name` (etc.) in `unix-signals-extension.c` and that in `tty-raw-extension.c`??

**Comment by stevebyan** [comment]
Hi Tony,

> On Feb 25, 2017, at 1:38 PM, Tony Garnock-Jones <notifications@github.com> wrote:
> 
> OK, this is weird. I've pinned it down to an interaction between ansi and unix-signals. This program runs fine on Linux, but not OSX 10.11.6:
> 
> #lang racket
> (
> require
>  ansi)
> (
> require unix-signals)
> When it fails, it fails with exactly the error you are seeing, Steve.
> 
> Could it be possible that there's some kind of linker-related interference between the scheme_module_name (etc.) in unix-signals-extension.c and that in tty-raw-extension.c??

I haven't tried to investigate it myself; I'm just a beginner at Racket. I do know that it worked fine in an earlier version of Mac OS X (maybe 10.11, maybe 10.10) and with an earlier version of Racket (maybe 6.7).

Best regards,
-Steve

--  
Steve Byan
stevebyan@me.com
Littleton, MA

**Comment by mflatt** [comment]
It appears that Mac OS wants `RTLD_LOCAL` in the `dlopen()` call, otherwise `dlsym()` searches through all previously open shared objects – even though `dlopen()` is given a specific library handle. That doesn't seem like reasonable behavior from `dlsym()`, but maybe I'm missing something.

I'll push a change to make extension loading using `RTLD_LOCAL` on Mac OS. I don't have a definite workaround for the current release, although it's possible that loading the shared object first via `ffi-lib` (which uses `RTLD_LOCAL`) could avoid the problem.

Beware that the extension in "ansi" doesn't seem to have any GC-cooperation annotations or build via xform.

**Comment by tonyg** [comment]
Thanks @mflatt! I've added [this change](https://github.com/tonyg/racket-ansi/commit/c2454badf7d9401425bab91ba44e4287e690607b) to racket-ansi which I hope fixes the issue with ansi.

**Comment by stevebyan** [comment]
rmacs is working fine now with the newer Racket releases.
